export const data = [
  { x: new Date().getTime(), y: 1037 },
  { x: new Date().setDate(new Date().getDate() - 10), y: 350 },
  { x: new Date().setDate(new Date().getDate() - 20), y: 1367 },
  { x: new Date().setDate(new Date().getDate() - 30), y: 694 },
  { x: new Date().setDate(new Date().getDate() - 40), y: 855 },
  { x: new Date().setDate(new Date().getDate() - 50), y: 450 },
  { x: new Date().setDate(new Date().getDate() - 60), y: 630 },
  { x: new Date().setDate(new Date().getDate() - 70), y: 1686 },
  { x: new Date().setDate(new Date().getDate() - 80), y: 586 },
  { x: new Date().setDate(new Date().getDate() - 90), y: 738 },
  { x: new Date().setDate(new Date().getDate() - 100), y: 1460 },
  { x: new Date().setDate(new Date().getDate() - 120), y: 485 },
  { x: new Date().setDate(new Date().getDate() - 140), y: 1257 },
  { x: new Date().setDate(new Date().getDate() - 160), y: 1300 },
  { x: new Date().setDate(new Date().getDate() - 180), y: 2455 },
  { x: new Date().setDate(new Date().getDate() - 200), y: 1300 },
  { x: new Date().setDate(new Date().getDate() - 220), y: 472 },
  { x: new Date().setDate(new Date().getDate() - 240), y: 1946 },
  { x: new Date().setDate(new Date().getDate() - 260), y: 1300 },
  { x: new Date().setDate(new Date().getDate() - 280), y: 697 },
  { x: new Date().setDate(new Date().getDate() - 300), y: 1500 },
];
